### PR TITLE
Windows and OS X builds removed

### PR DESCRIPTION
**Pull request by offa**
Windows and OS X builds removed, see #11.

### CODE REVIEW

**Comment by offa** [comment]
Both changes are separate commits, so they are easily revertible once the builds are fixed.

**Comment by offa** [comment]
I see ... AppVeyor isn't disabled by simply removing it's config ...

**Comment by bryceschober** [comment]
I'm gonna go ahead and merge, and see if maybe AppVeyor will disable itself once in master

**Comment by bryceschober** [comment]
@offa well, I enabled the "Skip branches without appveyor.yml" setting, and that doesn't seem to have helped. Maybe that only applies to choosing to build or not, and doesn't apply when I click the build now button.

... And I don't have admin on this project to disable the integration from the github side.

... So I ended up changing the AppVeyor setting for Build type to "Off".

**Comment by offa** [comment]
I guess @basvodde can do this. At least we have a green master now! :+1:

**Pull request merged**
